name: Format

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  format:
    name: Format
    if: github.repository_owner == 'withastro'
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max_old_space_size=4096"
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          # Needs access to push to main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup PNPM
        uses: pnpm/action-setup@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Format code
        run: pnpm run format:ci

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[ci] format"
          branch: ${{ github.head_ref }}
          commit_user_name: astrobot-houston
          commit_user_email: fred+astrobot@astro.build
